
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@emotion/react";
import webTheme from "./theme";
import CssBaseline from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
        <body className={inter.className}>{children}</body>
    </html>
  );
}
